log:
  level: INFO

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "saahil.1609.bhavsar@gmail.com"
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: "Host(`example.com`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: dlops-project
      tls:
        certResolver: letsencrypt

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    streamlit_app:
      loadBalancer:
        servers:
          - url: http://streamlit_app:8501

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
